### PR TITLE
migrate 5.5 docs to the Antora documentation structure and modern AsciiDoc

### PR DESCRIPTION
**Pull request by mojavelinux**
This pull request migrates the 5.5 (vulcan) docs and build script to the Antora documentation structure and modern AsciiDoc.

The files in the docs folder are ready to be used directly in the documentation build pipeline for the new Couchbase documentation site. The provided script (generate.sh) can also be used to generate standalone HTML and man pages as before. The script has been updated to use Asciidoctor and an Asciidoctor extension instead of AsciiDoc Python and xmlto. Information can be found in the updated README.

Finally, several patches were made to the content to fix syntax errors that were preventing the pages from converting cleaning. No changes were made to the content material itself.

### CODE REVIEW

**Comment by mojavelinux** [comment]
cc: @amarantha-k 

If changes are requested, I can update this PR as needed.

**Comment by mojavelinux** [comment]
There will be corresponding PRs for 5.1 and 5.0 as well. However, in order to submit those, I need to know which branches to target.

**Comment by mikewied** [comment]
Merged upstream.

**Comment by mojavelinux** [comment]
@mikewied we'll need these changes for the alice branch (server 6.0) as well. Should I submit directly to gerrit?

**Pull request closed without merging**
